import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderMarkdown, escapeHtml as e } from './markdown.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const pages = JSON.parse(await readFile(path.join(root, 'content/manifest.json'), 'utf8'));
const sources = JSON.parse(await readFile(path.join(root, 'content/sources.json'), 'utf8'));
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
await cp(path.join(root, 'assets'), path.join(out, 'assets'), { recursive: true });
const groups = [...new Set(pages.map(p => p.group))];
const svgArrow = '<span aria-hidden="true">↗</span>';
const chapterNumber = p => String(pages.findIndex(x => x.slug === p.slug) + 1).padStart(2, '0');
function sidebar(current) {
  return `<nav aria-label="学習ガイド" class="sidebar" id="sidebar"><a class="overview-link ${current === 'index' ? 'active' : ''}" href="index.html" ${current === 'index' ? 'aria-current="page"' : ''}>学習ガイドの全体像</a>${groups.map((g, i) => `<div class="nav-group"><p class="group-label"><span>${String(i + 1).padStart(2, '0')}</span>${e(g)}</p>${pages.filter(p => p.group === g).map(p => `<a data-slug="${p.slug}" class="chapter-link ${p.slug === current ? 'active' : ''}" href="${p.slug}.html" ${p.slug === current ? 'aria-current="page"' : ''}><span class="chapter-no">${chapterNumber(p)}</span><span>${e(p.title.split('：')[0])}</span><span class="read-indicator" aria-hidden="true"></span></a>`).join('')}</div>`).join('')}<div class="nav-footer"><p>あなたの学習メモ</p><span id="progress-label">0 / ${pages.length} ページ読了</span><progress id="progress-bar" max="${pages.length}" value="0" aria-label="読了したページ数"></progress><button type="button" id="reset-progress" class="text-button">読了記録をリセット</button></div></nav>`;
}
function demo(name) {
  if (name === 'request') return `<section class="lab" data-lab="request" aria-label="リクエストを組み立てるデモ"><div class="lab-heading"><span class="eyebrow">リクエストを組み立てる</span><span class="mock-tag">API通信なし</span></div><label for="request-type">質問の種類</label><select id="request-type"><option value="choice">Choice — 1つを選ぶ</option><option value="score">Score — 段階で評価する</option><option value="noul">Noul — はいの確率を返す</option></select><label for="request-state">State：判断させたい文章</label><textarea id="request-state" rows="3" maxlength="4000">予定を保存するとエラーが出て、登録できません。</textarea><p class="lab-hint">下のJSONが変わります。入力の分類や推論はしません。</p><div class="code-block"><div class="code-top"><span>送信するJSONの形</span><button type="button" class="copy-code">コピー</button></div><pre tabindex="0"><code id="request-output"></code></pre></div></section>`;
  if (name === 'noul') return `<section class="lab" data-lab="noul" aria-label="Noulのしきい値デモ"><div class="lab-heading"><span class="eyebrow">しきい値を試す</span><span class="mock-tag">架空の入力値</span></div><label for="noul-p">はいの確率を自分で設定：<output id="noul-value" for="noul-p">0.50</output></label><input id="noul-p" type="range" min="0" max="100" value="50"><div class="range-scale"><span>0.0 / いいえ側</span><span>1.0 / はい側</span></div><div id="noul-route" class="route-result" aria-live="polite"></div><p class="lab-hint">0.2 / 0.8は教材用の境界です。実際のJevの予測値ではありません。</p></section>`;
  if (name === 'score') return `<section class="lab" data-lab="score" aria-label="Scoreの期待値計算デモ"><div class="lab-heading"><span class="eyebrow">分布と平均の関係</span><span class="mock-tag">手動で計算</span></div>${[0,1,2].map((n) => `<label for="score-${n}">段階${n}の重み <output id="weight-${n}" for="score-${n}">${[0,50,50][n]}</output></label><input id="score-${n}" type="range" min="0" max="100" value="${[0,50,50][n]}">`).join('')}<div id="score-result" class="score-result" aria-live="polite"></div><p class="lab-hint">重みを合計で割って確率に直します。confidenceは計算していません。</p></section>`;
  throw new Error(`Unknown demo: ${name}`);
}
function layout({ slug, title, description, body, toc = '', group = '', chapter = null }) {
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${e(description)}"><meta name="color-scheme" content="light dark"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'none'; font-src 'self'; object-src 'none'; base-uri 'none'; form-action 'none'"><title>${e(title)} | Jev 日本語ガイド（非公式）</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css"><link rel="stylesheet" href="assets/reading.css"><script src="assets/theme.js"></script></head><body data-page="${slug}"><a class="skip-link" href="#main">本文へスキップ</a><div class="notice">非公式の日本語学習ガイド <span class="notice-detail">／ TypeSafe AIとは無関係・非公認です</span><a href="about.html">編集方針 ${svgArrow}</a></div><header class="site-header"><a href="index.html" class="brand" aria-label="Jev 日本語ガイド ホーム"><span class="brand-mark" aria-hidden="true">j.</span><span>Jev <span class="brand-sub">日本語ガイド</span></span></a><span class="header-label">判断を、コードの中へ。</span><div class="header-actions"><button type="button" id="open-search" class="search-button"><span aria-hidden="true">⌕</span><span>ガイド内を検索</span><kbd>⌘ K</kbd></button><a class="official-link" href="https://docs.typesafe.ai/" rel="noreferrer">公式Docs ${svgArrow}</a><button type="button" id="theme-toggle" aria-label="ダークモードに切り替える" title="表示テーマを切り替える">◐</button><button type="button" id="menu-toggle" aria-label="学習メニューを開く" aria-expanded="false" aria-controls="sidebar">☰</button></div></header><div class="page-shell">${sidebar(slug)}<div class="mobile-backdrop" id="mobile-backdrop"></div><main id="main" tabindex="-1" class="${slug === 'index' ? 'home' : 'document'}">${slug !== 'index' ? `<div class="breadcrumb"><a href="index.html">学習ガイド</a><span>/</span><span>${e(group)}</span></div>` : ''}${body}<footer class="site-footer"><div><strong>Jev 日本語ガイド</strong><span>非公式・独立した学習教材</span></div><p>仕様確認日：2026年9月21日。変更される情報は、必ず公式資料を確認してください。</p><a href="sources.html">出典と確認範囲</a></footer></main>${toc ? `<aside class="toc" aria-label="このページの目次"><p>このページの内容</p>${toc}<div class="toc-note"><span class="status-dot"></span> 仕様確認：2026.09.21<br>実API未検証の教材です。</div></aside>` : ''}</div><dialog id="search-dialog" aria-labelledby="search-title"><div class="search-top"><h2 id="search-title">ガイド内を検索</h2><button id="close-search" type="button" aria-label="検索を閉じる">×</button></div><label for="search-input" class="sr-only">検索する言葉</label><input id="search-input" type="search" placeholder="例：確率、APIキー、TypeScript" autocomplete="off"><p id="search-status" role="status">日本語の本文・見出し・用語から検索できます。</p><div id="search-results"></div></dialog><div id="toast" class="toast" role="status"></div><script src="assets/search-data.js"></script><script src="assets/lab.js"></script><script src="assets/app.js"></script></body></html>`;
}
const searchData = [];
for (const p of pages) {
  if (!/^[a-z0-9-]+$/.test(p.slug)) throw new Error(`Invalid slug: ${p.slug}`);
  const markdown = await readFile(path.join(root, `content/${p.slug}.md`), 'utf8');
  const headings = [];
  const article = renderMarkdown(markdown, { demo, headings, blockSections: true });
  const idx = pages.findIndex(x => x.slug === p.slug);
  const sourceHTML = p.sources.map(key => { const s = sources[key]; if (!s) throw new Error(`Unknown source: ${key}`); return `<a href="${e(s.url)}" rel="noreferrer">${e(s.title)} ${svgArrow}</a>`; }).join('');
  const pager = `<nav class="pager" aria-label="前後のページ">${idx > 0 ? `<a href="${pages[idx-1].slug}.html"><span>← 前のページ</span><strong>${e(pages[idx-1].title.split('：')[0])}</strong></a>` : '<span></span>'}${idx < pages.length-1 ? `<a class="next" href="${pages[idx+1].slug}.html"><span>次のページ →</span><strong>${e(pages[idx+1].title.split('：')[0])}</strong></a>` : `<a class="next" href="index.html"><span>全体像に戻る →</span><strong>学習ガイドのホーム</strong></a>`}</nav>`;
  const body = `<article><header class="article-header"><div class="eyebrow">${chapterNumber(p)} / ${e(p.group)}</div><h1>${e(p.title)}</h1><p class="article-lead">${e(p.summary)}</p><div class="article-meta"><span>公式資料を基にした独自解説</span><span>確認日 ${e(p.checked)}</span></div></header><div class="learning-goal"><span>このページのゴール</span><p>${e(p.goal)}</p></div><div class="prose">${article}</div><section class="source-block" aria-label="参照した公式資料"><h2>参照した公式資料</h2><p>本文の仕様説明は以下を参照。教材の例・しきい値・設計案は独自に作成しています。</p><div>${sourceHTML}</div></section><div class="read-action"><p>ここまで理解できたら、次へ。</p><button type="button" id="mark-read" data-slug="${p.slug}">読了にする</button></div>${pager}</article>`;
  const toc = '<a href="#chapter-brief-title">先に、3つの要点</a>' + headings.filter(h => h.level === 2).map(h => `<a href="#${h.id}">${e(h.title)}</a>`).join('');
  await writeFile(path.join(out, `${p.slug}.html`), layout({ slug: p.slug, title: p.title, description: p.summary, group: p.group, body, toc }));
  const text = markdown.replace(/```[\s\S]*?```/g, ' ').replace(/\[([^\]]+)\]\([^)]+\)/g, '$1').replace(/[#*`|]/g, '').replace(/:::[^\n]*/g, '').replace(/\s+/g, ' ').trim();
  searchData.push({ slug: p.slug, title: p.title, group: p.group, summary: p.summary, keywords: p.keywords, text });
}
const cards = [
  { n:'01', label:'はじめる', title:'まずは、1つの判断から。', text:'Jevの役割を知り、公式のPlaygroundで短い文章を試す。', link:'start', label2:'最初の一歩へ' },
  { n:'02', label:'理解する', title:'3つの型を、使い分ける。', text:'Choice・Score・Noul。返ってきた値の意味を、手を動かして学ぶ。', link:'question-types', label2:'基本概念を学ぶ' },
  { n:'03', label:'つくる', title:'判断を、サービスの中へ。', text:'APIの呼び出しから、評価・安全対策・応用パターンまで。', link:'javascript-sdk', label2:'実装へ進む' }
];
const homeBody = `<section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> はじめてのJev / 日本語で学ぶ</div><h1>Jevを、<br><span>判断に使いこなす。</span></h1><p class="hero-lead">「何ができる？」から、<br>「自分のサービスで使える」まで。</p><p class="hero-description">まずは3つの要点と図解から。<br class="desktop-break">基本・実装・応用を、ひとまとまりずつ学べるガイドです。</p><div class="hero-actions"><a class="button-primary" href="start.html">はじめから学ぶ <span>→</span></a><a class="button-secondary" href="request-builder.html">APIなしで構造を試す</a></div><p class="hero-note">非公式・日本語の独自解説 / 登録不要 / 全${pages.length}章</p></div><div class="concept-panel" aria-label="文章をJevで判断し、コードで処理する流れ。説明用であり実行結果ではありません。"><div class="panel-caption"><span>小さな判断を、組み合わせる。</span><span>CONCEPT</span></div><div class="input-card"><span class="tiny-label">01 / STATE</span><p>「予定を保存すると<br>エラーになります」</p></div><div class="connector-line" aria-hidden="true">↓</div><div class="decision-card"><div><span class="decision-symbol">J</span><strong>Jev</strong></div><span>何についての問い合わせ？</span></div><div class="connector-line" aria-hidden="true">↓</div><div class="result-card"><span class="tiny-label">02 / CHOICE</span><div><code>bug</code><span>不具合の報告</span></div></div><div class="code-note"><span>03 / YOUR CODE</span><p>候補ラベルを付ける<br><strong>処理を決めるのは、コード。</strong></p></div><p class="panel-note">説明用の期待値です。実際の推論結果ではありません。</p></div></section><section class="home-intro"><div><span class="eyebrow">LEARNING PATH</span><h2>順番に読む。必要な章に戻る。</h2></div><p>前半はコードを書かずに。<br>後半はJavaScript / TypeScriptを中心に。</p></section><div class="path-grid">${cards.map(c => `<a href="${c.link}.html" class="path-card"><div class="path-top"><span>${c.n}</span><span>${c.label}</span></div><h3>${c.title}</h3><p>${c.text}</p><div class="path-cta">${c.label2}<span>↗</span></div></a>`).join('')}</div><section class="home-warning"><span class="warning-symbol" aria-hidden="true">!</span><div><h2>「型どおりに返る」と「判断が正しい」は、別のこと。</h2><p>日本語での精度検証、不確かな結果の扱い、APIキーの保護まで。使い始める前に知っておきたい注意点も、一緒に学びます。</p><a href="limitations.html">できること・苦手なことを確認する →</a></div></section><section class="curriculum"><div class="section-title"><span class="eyebrow">CONTENTS</span><h2>入門から応用までの道順</h2></div>${groups.map((g,i) => `<div class="curriculum-group"><div class="curriculum-heading"><span>${String(i+1).padStart(2,'0')}</span><h3>${e(g)}</h3></div><div>${pages.filter(p=>p.group===g).map(p=>`<a href="${p.slug}.html"><span>${e(p.title)}</span><span aria-hidden="true">↗</span></a>`).join('')}</div></div>`).join('')}</section><section class="home-end"><div><span class="eyebrow">SOURCE FIRST</span><h2>原典に戻れる、日本語ガイド。</h2><p>各ページに公式の出典と確認日を掲載。独自の教材、設計案、未検証の箇所を区別しています。</p></div><a href="sources.html" class="button-secondary">出典と確認範囲を見る ↗</a></section>`;
await writeFile(path.join(out, 'index.html'), layout({ slug: 'index', title: '入門から応用まで', description: 'Jevの基本概念からAPI実装・応用・精度評価まで。公式資料を基にした、非公式の日本語学習ガイド。', body: homeBody }));
await writeFile(path.join(out, 'assets/search-data.js'), `globalThis.JEV_SEARCH_DATA = ${JSON.stringify(searchData).replaceAll('<','\\u003c')};\n`);
await writeFile(path.join(out, '.nojekyll'), '');
await mkdir(path.join(out, 'examples'), { recursive: true });
await cp(path.join(root, 'examples'), path.join(out, 'examples'), { recursive: true });
await writeFile(path.join(out, 'build-info.json'), JSON.stringify({ version: '0.2.0', verifiedDate: '2026-09-21', articles: pages.length, apiCallsDuringBuild: 0 }, null, 2));
console.log(`Built ${pages.length} articles + homepage. No network access / no API keys used.`);
